const { v4: uuidv4 } = require("uuid");

const sampleDonor = [
  {
    name: "Aarav Sharma",
    dob: new Date("1998-05-14"),
    phone: "9876543210",
    email: "aarav.sharma@example.com",
    address: "Guwahati, Assam",
    blood_grp: "A+",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-01"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Priya Das",
    dob: new Date("1996-11-20"),
    phone: "9123456780",
    email: "priya.das@example.com",
    address: "Silchar, Assam",
    blood_grp: "O+",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-02"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Aarav Sharma",
    dob: new Date("1998-03-12"),
    phone: "9876543210",
    email: "aarav.sharma@example.com",
    address: "Delhi",
    blood_grp: "O+",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-02"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*02:01, B*15:01, DRB1*04:01",
    status: "Submitted",
    test_date: new Date("2026-07-08"),
  },

  {
    name: "Rahul Verma",
    dob: new Date("1994-02-10"),
    phone: "9988776655",
    email: "rahul.verma@example.com",
    address: "Delhi",
    blood_grp: "B+",
    gender: "Male",
    med_con: "Diabetes",
    received_date: new Date("2026-07-03"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Sneha Reddy",
    dob: new Date("2000-08-19"),
    phone: "9123456789",
    email: "sneha.reddy@example.com",
    address: "Hyderabad, Telangana",
    blood_grp: "B+",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-04"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*24:02, B*35:01, DRB1*15:01",
    status: "Submitted",
    test_date: new Date("2026-07-10"),
  },

  {
    name: "Sneha Roy",
    dob: new Date("2000-08-25"),
    phone: "9871203456",
    email: "sneha.roy@example.com",
    address: "Kolkata, West Bengal",
    blood_grp: "AB+",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-04"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Rohan Mehta",
    dob: new Date("1997-11-05"),
    phone: "9988776655",
    email: "rohan.mehta@example.com",
    address: "Ahmedabad, Gujarat",
    blood_grp: "A-",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-06"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*01:01, B*08:01, DRB1*03:01",
    status: "Submitted",
    test_date: new Date("2026-07-12"),
  },

  {
    name: "Rohan Mehta",
    dob: new Date("1993-01-18"),
    phone: "9012345678",
    email: "rohan.mehta@example.com",
    address: "Mumbai, Maharashtra",
    blood_grp: "O-",
    gender: "Male",
    med_con: "Hypertension",
    received_date: new Date("2026-07-05"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },
  {
    name: "Ananya Sen",
    dob: new Date("1999-03-12"),
    phone: "8765432109",
    email: "ananya.sen@example.com",
    address: "Shillong, Meghalaya",
    blood_grp: "A-",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-06"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },
  {
    name: "Meera Nair",
    dob: new Date("1999-02-27"),
    phone: "9090909090",
    email: "meera.nair@example.com",
    address: "Kochi, Kerala",
    blood_grp: "AB+",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-07"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*03:01, B*07:02, DRB1*13:01",
    status: "Submitted",
    test_date: new Date("2026-07-14"),
  },

  {
    name: "Karan Singh",
    dob: new Date("1995-09-30"),
    phone: "9090909090",
    email: "karan.singh@example.com",
    address: "Patna, Bihar",
    blood_grp: "B-",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-07"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Meera Nair",
    dob: new Date("1997-12-08"),
    phone: "9345678123",
    email: "meera.nair@example.com",
    address: "Kochi, Kerala",
    blood_grp: "AB-",
    gender: "Female",
    med_con: "Asthma",
    received_date: new Date("2026-07-08"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Karan Singh",
    dob: new Date("1996-09-14"),
    phone: "9812345678",
    email: "karan.singh@example.com",
    address: "Lucknow, Uttar Pradesh",
    blood_grp: "O-",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-09"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*11:01, B*40:01, DRB1*09:01",
    status: "Submitted",
    test_date: new Date("2026-07-16"),
  },

  {
    name: "Vikram Patel",
    dob: new Date("1992-06-16"),
    phone: "9556677889",
    email: "vikram.patel@example.com",
    address: "Ahmedabad, Gujarat",
    blood_grp: "O+",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-09"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Priya Das",
    dob: new Date("2001-06-22"),
    phone: "9870012345",
    email: "priya.das@example.com",
    address: "Kolkata, West Bengal",
    blood_grp: "B-",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-11"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*26:01, B*38:01, DRB1*11:01",
    status: "Submitted",
    test_date: new Date("2026-07-18"),
  },

  {
    name: "Ishita Gupta",
    dob: new Date("2001-04-04"),
    phone: "9811223344",
    email: "ishita.gupta@example.com",
    address: "Jaipur, Rajasthan",
    blood_grp: "A+",
    gender: "Female",
    med_con: "None",
    received_date: new Date("2026-07-10"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "",
    status: "Pending",
    test_date: "",
  },

  {
    name: "Aditya Joshi",
    dob: new Date("1998-12-30"),
    phone: "9765432109",
    email: "aditya.joshi@example.com",
    address: "Pune, Maharashtra",
    blood_grp: "A+",
    gender: "Male",
    med_con: "None",
    received_date: new Date("2026-07-13"),
    sample_id: uuidv4(),
    donor_id: uuidv4(),
    HLA_type: "A*30:01, B*13:02, DRB1*07:01",
    status: "Submitted",
    test_date: new Date("2026-07-20"),
  },
];

module.exports = { donorData: sampleDonor };
